# These are supported funding model platforms

github: [masajid390] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ["https://www.paypal.com/paypalme/masajid390"]
